baseURL = 'https://sendipad.github.io/flexirule-docs/'
languageCode = 'en-US'
title = 'FlexiRule Docs'
theme = 'doks'

# For Doks theme
defaultContentLanguage = 'en'
defaultContentLanguageInSubdir = true

[languages]
  [languages.en]
    languageName = 'English'
    contentDir = 'content/en'
    weight = 10
    [languages.en.params]
      languageISO = 'EN'
      languageTag = 'en-US'
      footer = '© 2024 FlexiRule. Built for the Frappe Ecosystem.'
      titleHome = 'FlexiRule Documentation'

[module]
  [[module.imports]]
    path = 'github.com/hidetake/hugo-doks'
